/* Autogenerated by script/mkversion.sh */
#define SAMBA_VERSION_MAJOR 3
#define SAMBA_VERSION_MINOR 0
#define SAMBA_VERSION_RELEASE 25
#define SAMBA_VERSION_PRE_RELEASE 1
#define SAMBA_VERSION_OFFICIAL_STRING "3.0.25pre1"
#define SAMBA_VERSION_STRING samba_version_string()
