; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-linux-wine32sp64 -O0 | FileCheck %s

define void @foo(i32 addrspace(32)* addrspace(32)* %p) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    leaq -{{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    addl $16, %ecx
; CHECK-NEXT:    movl %ecx, (%edi)
; CHECK-NEXT:    retq
  %a = alloca i32, i32 10
  %addr = getelementptr i32, i32* %a, i32 4
  %addr.0 = addrspacecast i32* %addr to i32 addrspace(32)*
  store i32 addrspace(32)* %addr.0, i32 addrspace(32)* addrspace(32)* %p
  ret void
}

