name: build

on: [push]

jobs:
  build:

    runs-on: [macos]

    steps:
    - uses: actions/checkout@v2
    - name: Install Homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: Install dependencies
      run: |
        brew install bison
        brew cask install xquartz
        brew install flex
        brew install mingw-w64
        brew install pkgconfig
    - name: Preconfiguring LLVM
      run: |
        cd llvm
        mkdir build
        cd build
        cmake ../
    - name: Compiling LLVM
      run: |
        cd llvm/build
        make -j8
    - name: Preconfiguring Clang
      run: |
        cd clang
        mkdir build
        cd build
        cmake ../
    - name: Compiling Clang
      run: |
        export PATH="$(pwd)/llvm/build/bin:$PATH"
        cd gnutls/
        make -j8
    - name: Compiling GnuTLS/gmp
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$PATH"
        cd gnutls/gmp
        ./configure
        make -j8
      env:
        CC: clang
        CXX: clang++
    - name: Compiling GnuTLS/nettle
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$PATH"
        cd gnutls/nettle
        ./configure
        make -j8
      env:
        CC: clang
        CXX: clang++
    - name: Compiling GnuTLS
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$PATH"
        cd gnutls/gmp
        ./configure
        make -j8
      env:
        CC: clang
        CXX: clang++
    - name: Compiling FreeType
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$PATH"
        cd freetype
        mkdir build
        cd build
        cmake ../
        make -j8
      env:
        CC: clang
        CXX: clang++
    - name: Compiling SMB3
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$PATH"
        cd samba3/source
        ./configure
        make -j8
      env:
        CC: clang
        CXX: clang++
    - name: Preconfiguring Wine
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$(pwd)/samba3/source:$(pwd)/freetype/build:$(pwd)/gnutls/gmp:$(pwd)/gnutls/gnutls:$(pwd)/gnutls/nettle:$PATH"
        cd wine
        ./configure --enable-win32on64
      env:
        CC: clang
        CXX: clang++
    - name: Compiling Wine
      run: |
        cd wine
        make -j7
    - name: Packaging LLVM
      run: tar -czvf clang-macos.tar.gz ./clang/build
    - name: Packaging LLVM
      run: tar -czvf llvm-macos.tar.gz ./llvm/build
    - name: Packaging Wine
      run: tar -czvf wine-macos.tar.gz ./wine
    - name: Move Artifacts
      run: |
        mkdir artifacts
        mv *.tar.gz ./artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Compiled Results
        # Directory containing files to upload
        path: artifacts
      
        
