name: build

on: [push]

jobs:
  build:

    runs-on: [macos]

    steps:
    - uses: actions/checkout@v2
    - name: Install Homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    - name: Install dependencies
      run: |
        brew install bison
        brew cask install xquartz
        brew install flex
        brew install mingw-w64
        brew install pkgconfig
    - name: Preconfiguring LLVM
      run: |
        cd llvm
        mkdir build
        cd build
        cmake ../
    - name: Compiling LLVM
      run: |
        cd llvm/build
        make -j7
    - name: Preconfiguring Clang
      run: |
        cd clang
        mkdir build
        cd build
        cmake ../
    - name: Compiling Clang
      run: |
        export PATH="$(pwd)/llvm/build/bin:$PATH"
        cd clang/build
        make -j7
    - name: Preconfiguring Wine
      run: |
        export PATH="$(pwd)/clang/build/bin:$(pwd)/llvm/build/bin:$PATH"
        cd wine
        ./configure --enable-win32on64
      env:
        CC: clang
        CXX: clang++
    - name: Compiling Wine
      run: |
        cd wine
        make -j7
    - name: Packaging Wine
      run: tar -czvf the-wine.tar.gz ./wine
    - name: Upload Release
      uses: yakuhzi/action-release@v1.2.0
      with:
        # File to upload to the release
        file: the-wine.tar.gz
      
        
